name: "nix-darwin"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v13

      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210429_d15a196/install
    # Configure Nix to enable flakes
    - run: echo "experimental-features = nix-command flakes" | sudo tee -a /etc/nix/nix.conf
    - name: Build Emacsng-Rust Dependency
      run: nix -Lv build .#emacsNg-rust
    - name: Build Emacsng
      run: nix -Lv build .#emacsNg
